project:
  type: website
execute:
  freeze: auto
website:
  navbar:
    background: "#27AAE1"  # Background color for navbar (menu part)
    alignment: "center"  # Center align menu items
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: "Schedule"
      - href: participants.qmd
        text: "Participants"
      - href: faculty.qmd
        text: "Faculty"

  back-to-top-navigation: true

  body-footer: |
    ![](images/logos.png){ width=860px style="display: block; margin: 0 auto;" }


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    include-in-header:
      - text: |
          <script src="js/participant-popup.js"></script>
